site_name: "Mòdul: Big Data Aplicat (CE IA i Big Data) Curs 25/26"

theme:
  name: material
  logo: img/logo.svg
  palette:
  primary: 'deep purple'

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search

extra_css:
  - styles/taules.css

nav:
  - "Inici": "index.md"
  - "Presentació": "documents/index.md"
  - "1. Introducció al Big Data": "u01/index.md"
  - "2. Elements i arquitectura Big Data": "u02/index.md"
  - "3.1 Repàs Docker": "u03/index.md"
  - "3.2 Docker Compose": "u03/annex.md"
  - "4.1 Introducció a Node-RED": "u04/index.md"
  - "4.2 Node-RED intermedi": "u04/nodered-intermedi.md"
  - "4.3 Node-RED avançat": "u04/nodered-avançat.md"
  - "4.4 Node-RED dashboards": "u04/nodered-dashboards.md"
  - "4.5 Formularis en Node-RED": "u04/nodered-formularis.md"
  - "5. Fiware. Orion. Context Broker": "u05/index.md"
  - "6. MQTT": "u06/index.md"